name: cs333finalproject

on:
  push:
    branches: [ main ]

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build and run Docker container
      run: |
        docker build -t my-pa2-app .
        docker run -it my-pa2-app bash -c "cat PA2_test.sql | python PA2.py"
